name: Release Deploy

on:
  release:
    types: [published]

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tagName.outputs.tag }}
            
  deploy-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: azure
      url: http://azure.monacloud.mvkaran.net
    
    steps:
       - name: Checkout repo
         uses: actions/checkout@v2
         
       - name: Set context from Kubeconfig
         uses: azure/k8s-set-context@v1
         with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }} 
          context: monacloud 
         id: setcontext

       - name: Get tag name
         uses: olegtarasov/get-tag@v2.1

       - name: Get new container image tag
         id: image-tag
         run: |
            echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"

       - name: Deploy to Kubernetes
         uses: Azure/k8s-deploy@v1
         with:
            manifests: |
              k8s.yaml
            images: |
              ${{ steps.image-tag.outputs.image }}

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: aws
      url: http://aws.monacloud.mvkaran.net

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set Kubeconfig
        run: |
         aws eks --region ap-south-1 update-kubeconfig --name monacloud 

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1

      - name: Get new container image tag
        id: image-tag
        run: |
            echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ steps.image-tag.outputs.image }}

  deploy-google-cloud:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: google-cloud
      url: http://gcp.monacloud.mvkaran.net

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get GKE credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: monacloud
          location: us-central1
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1

      - name: Get new container image tag
        id: image-tag
        run: |
            echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ steps.image-tag.outputs.image }}
  
      
